# Pandas Lecture Lab Activity

What is CRUD?

In [2]:
#CRUD stands for the following: Create, Read, Update, and Delete.

Using pandas import the Module 7 Lecture Lab Activity.csv

In [3]:
import pandas as pd

In [4]:
candy = pd.read_csv("Module 7 Lecture Lab Activity.csv", encoding="latin-1")

Show the header for the CSV.

In [5]:
(candy.head())

             Names                                    Type of Candy   Cost
0           Damien                                       Almond Joy   1.96
1   adalynn gilman                                           Reeses   1.48
2  Noah Papenbrock  Hershey's Special Dark Zero Sugar Chocolate Bar   2.48
3            Mrwan                                         Snickers   1.00
4       Trenton Ly                                          Reese's  23.87

Show the first 15 rows of the CSV.

In [6]:
(candy.head(15))

                 Names                                    Type of Candy   Cost
0               Damien                                       Almond Joy   1.96
1       adalynn gilman                                           Reeses   1.48
2      Noah Papenbrock  Hershey's Special Dark Zero Sugar Chocolate Bar   2.48
3                Mrwan                                         Snickers   1.00
4           Trenton Ly                                          Reese's  23.87
5   alexander kauffman                                       Almond Joy   1.48
6       William Espich                                         Skittles   3.28
7             Andres H                                           reeces   1.20
8       Blake Tippmann                                     3 musketeers   1.48
9          Elijah Kite                                   Jolly Ranchers  18.69
10    Nick Schuhmacher                                            mints   1.50
11        Kevin Nguyen                                         Snickers   0.98
12       Chase McCarel                                        Milky Way   0.74
13                 Eja                             Skittles (50 oz bag)   9.98
14      Sarah Martinez                                             Twix   0.88

Show the last 7 rows of the CSV.

In [7]:
(candy.tail(7))

                 Names            Type of Candy  Cost
106      Jaxon Worrell           Jolly Ranchers  0.99
107             Emmett                   take 5  0.99
108      Michael Drane  Trolli sour gummy worms  0.99
109        Sean Wilson  Mike N Ikes or Skittles  1.99
110               izzy              gummy bears  1.99
111              brina                   reeses  1.99
112  kennedy ledbbeter            almond heresy  1.99

Show all the Columns of the CSV.

In [8]:
candy.columns

Index(['Names', 'Type of Candy', 'Cost'], dtype='str')

Show the specific data types of the CSV.

In [9]:
candy.dtypes
(candy.info())

<class 'pandas.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Names          113 non-null    str
 1   Type of Candy  113 non-null    str
 2   Cost           113 non-null    float64
dtypes: float64(1), str(2)
memory usage: 2.8 KB

Show a statistical summary of the CSV.

In [10]:
(candy.describe())

             Cost
count  113.000000
mean     2.391416
std      3.623166
min      0.740000
25%      0.990000
50%      1.160000
75%      1.990000
max     23.870000

What objects are not included in the statistical summary?
How can I get the objects that are not included?

In [11]:
"""When running the statistical summary, 
the numeric columns are added like ints and floats"""
"""When running the statistical summary,
the text strings or mixed data are not added"""
"""candy.describe(include="all")"""

'candy.describe(include="all")'

In [12]:
(candy.describe(include="all"))

         Names Type of Candy        Cost
count      113           113  113.000000
unique      53            75         NaN
top     Damien      Snickers         NaN
freq         3             6         NaN
mean       NaN           NaN    2.391416
std        NaN           NaN    3.623166
min        NaN           NaN    0.740000
25%        NaN           NaN    0.990000
50%        NaN           NaN    1.160000
75%        NaN           NaN    1.990000
max        NaN           NaN   23.870000

Show how to filter the names from the rest of the table?

In [13]:
(candy["Names"])

0                 Damien
1         adalynn gilman
2        Noah Papenbrock
3                  Mrwan
4             Trenton Ly
             ...
108        Michael Drane
109          Sean Wilson
110                 izzy
111                brina
112    kennedy ledbbeter
Name: Names, Length: 113, dtype: str

Show me the unique names.

In [14]:
(candy["Names"].nunique())

53

Show me only the rows that are under $1.00

In [15]:
(candy[candy["Cost"] < 1.00])

                          Names                Type of Candy  Cost
11                 Kevin Nguyen                     Snickers  0.98
12                Chase McCarel                    Milky Way  0.74
14               Sarah Martinez                         Twix  0.88
16                      brianna                     Snickers  0.98
23                        Allan                  Hershey Bar  0.88
25                  Bryce Bland           Hersheys Candy Bar  0.88
32              Noah Papenbrock      Great Value Peach Rings  0.98
38               Blake Tippmann                butter finger  0.98
42                Chase McCarel                         Twix  0.88
44               Sarah Martinez  Hershey's Cookies and Cream  0.88
46                      brianna                   Almond Joy  0.88
54                          Kim          Hershey's Chocolate  0.88
59                     edaevion                       KitKat  0.82
61                  Ethan Morse               reese's take 5  0.99
62               Blake Tippmann                      Reese's  0.99
69                Gabriel Moore                  jelly beans  0.99
70                      brianna                      kitkats  0.99
73                 Audrey marks                     skittles  0.99
74                  Xayne Blair                     Kit Kats  0.99
79                  Bryce Bland                     Snickers  0.99
80                         Troy                        Nerds  0.99
81                      shaheim              sour patch kids  0.99
82                jasiah waxton                         Twix  0.99
96                        faith                      Kit Kat  0.99
102  Nor Aisa Binti Abdul Molna                       Crunch  0.99
103                      Sa Hay                      Hershey  0.99
106               Jaxon Worrell               Jolly Ranchers  0.99
107                      Emmett                       take 5  0.99
108               Michael Drane      Trolli sour gummy worms  0.99

Show only the rows 17 to 37

In [16]:
(candy.iloc[17:38])

                 Names               Type of Candy  Cost
17          Cathy Wise                     Snicker  1.19
18              alexis                 Gummy Bears  1.00
19        Audrey marks                   heath bar  1.63
20         Xayne Blair                    Skittles  2.28
21       Corban Saylor                3 musketeers  1.48
22            Langston                      Reeses  1.96
23               Allan                 Hershey Bar  0.88
24                 Kim           Reese's Chocolate  1.48
25         Bryce Bland          Hersheys Candy Bar  0.88
26                Troy      cookie n crème Hershey  1.48
27             shaheim                  Candy Corn  2.28
28       jasiah waxton  Kit Kat Minis, White Creme  2.98
29            edaevion                  Almond Joy  1.64
30              Damien                     Reece's  2.06
31      adalynn gilman                  Lifesavers  5.28
32     Noah Papenbrock     Great Value Peach Rings  0.98
33               Mrwan               Reeses take 5  2.98
34          Trenton Ly                    Kit Kats  9.94
35  alexander kauffman                      KitKat  1.48
36      William Espich                   Starburst  9.98
37            Andres H                    snickers  1.16

Show only the rows that are for Damien.

In [17]:
candy[candy["Names"] == "Damien"]

     Names Type of Candy  Cost
0   Damien    Almond Joy  1.96
30  Damien       Reece's  2.06
84  Damien       Reese's  1.99

Create a new column names is_candy and make all the rows True

In [18]:
candy["is_candy"] = True

Change the name of the row you created to Candy.

In [19]:
candy = candy.rename(index={"is_candy": "Candy"})

Write an statement that iterates through the list and finds all the Snicker or snickers

In [20]:
(candy[candy["Type of Candy"].str.contains("snicker", case=False)])

            Names Type of Candy  Cost  is_candy
3           Mrwan      Snickers  1.00      True
11   Kevin Nguyen      Snickers  0.98      True
16        brianna      Snickers  0.98      True
17     Cathy Wise       Snicker  1.19      True
37       Andres H      snickers  1.16      True
45  Gabriel Moore  snickers bar  1.48      True
71     Cathy Wise      Snickers  1.99      True
77          Allan      snickers  1.99      True
79    Bryce Bland      Snickers  0.99      True
97      Juan Ruiz      Snickers  1.06      True

Using iloc change the 3rd row's candy column to False

In [21]:
candy.iloc[2,1] = "False"

Output the table to a csv named 'your_last_name_mod7output.csv'

In [22]:
candy.to_csv("Ganion_mod7output.csv")

Drop the candy column permanently

In [25]:
candy.drop("is_candy", axis=1)

                 Names            Type of Candy   Cost
0               Damien               Almond Joy   1.96
1       adalynn gilman                   Reeses   1.48
2      Noah Papenbrock                    False   2.48
3                Mrwan                 Snickers   1.00
4           Trenton Ly                  Reese's  23.87
..                 ...                      ...    ...
108      Michael Drane  Trolli sour gummy worms   0.99
109        Sean Wilson  Mike N Ikes or Skittles   1.99
110               izzy              gummy bears   1.99
111              brina                   reeses   1.99
112  kennedy ledbbeter            almond heresy   1.99

[113 rows x 3 columns]

# Please turn in the completed Juypter Notebook along with your output csv to github. Make sure that I can see the notebook and it is not just the file as this sometimes does not work. A link to the location on the repo should be submitted.